# version: 1.0.0
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """$os\
$sudo\
$directory\
$git_branch\
$git_status\
$git_commit\
$git_state\
$git_metrics\
$hostname\
$localip\
$shlvl\
$shell\
$env_var\
$jobs\
$username\
$fill\
$singularity\
$kubernetes\
$vcsh\
$fossil_branch\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$solidity\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$conda\
$meson\
$spack\
$memory_usage\
$aws\
$gcloud\
$openstack\
$azure\
$crystal\
$custom\
$status\
$cmd_duration\
$time\
$line_break\
$character"""

[fill]
symbol = ' '

[character]
format = "$symbol "
success_symbol = '[❯](bold #5FD700)'
error_symbol = "[✖](bold #FF0000)"

[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
symbol = " "
style = "bold #BC4AFF"
disabled = false

[username]
style_user = "bright-yellow bold italic"
style_root = "purple bold italic"
format = "[$user]($style) "
disabled = false
show_always = false

[directory]
read_only = " 󰌾"
truncate_to_repo = true
truncation_length = 0
use_os_path_sep = true
style = " #0087AF"
repo_root_style = 'bold #00AFFF'
repo_root_format = "[$before_root_path]($before_repo_root_style)[ $repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "

[cmd_duration]
format = " [ $duration](dimmed white)"
show_notifications = false

[time]
format = " [ $time]($style)"
disabled = false
style = "dimmed blue"

[jobs]
format = "[$symbol$number]($style)  "
style = "white"

[localip]
ssh_only = true
format = " ◯[$localipv4](bold magenta)"
disabled = false

[git_branch]
symbol = " "
format = "[$symbol$branch(:$remote_branch) ]($style)"
style = "bold #5FD700"
only_attached = true

[git_metrics]
added_style = 'italic dimmed green'
deleted_style = 'italic dimmed red'
ignore_submodules = true
disabled = true

[git_status]
style = "bold #D4AC02"
ahead = "⇡${count}"
behind = "⇣${count}"
modified = "!${count}"
deleted = "[✘${count}](red)"
format = "([$all_status$ahead_behind]($style) )"

[deno]
format = "[deno](italic) [∫ $version](green bold)"
version_format = "${raw}"

[lua]
symbol = " "
format = " [${symbol}${version}]($style)"
version_format = "${raw}"
style = "bold bright-yellow"

[nodejs]
symbol = "󰎙 "
format = " [$symbol($version)]($style)"
version_format = "${raw}"
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
symbol = " "
format = " [${symbol}${version}]($style)"
version_format = "${raw}"

[ruby]
format = " [$symbol($version)]($style)"
symbol = " "

[rust]
symbol = "󱘗 "
format = " [$symbol$version]($style)"

[package]
symbol = "󰏗 "
format = "[$symbol$version]($style)"
version_format = "${raw}"
style = "italic 208"

[swift]
format = " [$symbol($version)]($style)"
symbol = " "

[aws]
disabled = true
format = " [$symbol($version)]($style)"
symbol = "  "

[buf]
format = " [$symbol($version)]($style)"
symbol = " "

[c]
# format = " [$symbol($version)]($style)"
format = " [$symbol($name)(-$version)]($style)"
symbol = " "
version_format = "${raw}"

[conda]
format = " [$symbol($version)]($style)"
symbol = " "

[dart]
symbol = " "
format = " [$symbol($version)]($style)"

[docker_context]
symbol = " "
format = "[$symbol$context]($style) "

[elixir]
symbol = " "
format = " [$symbol($version)]($style)"

[elm]
symbol = " "
format = " [$symbol($version)]($style)"

[golang]
symbol = " "
format = " [$symbol($version)]($style)"

[haskell]
symbol = " "
format = " [$symbol($version)]($style)"

[java]
symbol = " "
format = " [$symbol($version)]($style)"

[julia]
symbol = " "
format = " [$symbol($version)]($style)"

[memory_usage]
symbol = "󰍛 "
format = " [$symbol${ram}( | ${swap})]($style)"
style = "bold dimmed red"
disabled = false
# threshold = 0

[nim]
symbol = "󰆥 "
format = " [$symbol($version)]($style)"

[spack]
format = " spack [$symbol$environment]($style)"

[cmake]
format = " [$symbol($version)]($style)"
symbol = " "

[crystal]
symbol = " "

[fennel]
symbol = " "

[fossil_branch]
symbol = " "

[git_commit]
tag_symbol = '  '

[guix_shell]
symbol = " "

[haxe]
symbol = " "
format = " [$symbol($version)]($style)"

[hg_branch]
symbol = " "

[hostname]
ssh_symbol = " "
ssh_only = true

[kotlin]
format = " [$symbol($version)]($style)"
symbol = " "

[meson]
format = " [$symbol($version)]($style)"
symbol = "󰔷 "

[ocaml]
format = " [$symbol($version)]($style)"
symbol = " "

[os]
disabled = false
style = "#98B0D3"

[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[perl]
format = " [$symbol($version)]($style)"
symbol = " "

[php]
format = " [$symbol($version)]($style)"
symbol = " "

[pijul_channel]
format = " [$symbol($version)]($style)"
symbol = " "

[rlang]
format = " [$symbol($version)]($style)"
symbol = "󰟔 "

[scala]
format = " [$symbol($version)]($style)"
symbol = " "

[zig]
format = " [$symbol($version)]($style)"
symbol = " "

[gradle]
symbol = " "
format = " [$symbol($version)]($style)"

